<a href="https://colab.research.google.com/github/IA-UNISON/IA-UNISON.github.io/blob/main/assets/libretas/Introducción%20a%20Numpy%20y%20Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Numpy y Matplotlib

**Curso Inteligencia Artificial 2026-1**

Julio Waissman

## Inicialización de una libreta

Vamos a introducir Numpy y Matplotlib, librerías para matemáticas y graficación, desde una libreta tipo *Jupyter*. Esta la puedes descargar y ejecutar en tu propia computadora, usando un editor de texto como VSCode, o inicializando Jupyter en linea de comando. Una opción muy popular es ejecutar la libreta en [Colaboratory](https://colab.google) de Google (que te permite ejecutar libretas en linea si cuantas con una cuenta de *Google*). Para ejecutar esta libreta en particular, lo puedes hacer [desde este enlace](https://colab.research.google.com/github/IA-UNISON/IA-UNISON.github.io/blob/main/assets/libretas/Introducción%20a%20Numpy%20y%20Matplotlib.ipynb).


Para inicializar la libreta y poderla utilizar con `numpy` y `matplotlib`, y asegurarse que los gráficos se presenten donde deben de estar es necesario ejecutar las siguientes instrucciones:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Para insertar las gráficas dentro del entorno
%matplotlib inline


Recuerda que hay que ejecutar cada celda (cell) con *ctrl-enter* o con el simbolo de la flechita arriba de la libreta.

La linea que empieza con `%` es un tipo de comando conocidos como *comandos mágicos*. En este comando le especificamos a la libreta que vamos a utilizar matplotlib para hacer gráficas y que queremos que las anexe dentro del documento. Existen muchos comandos mágicos, algunos muy útiles que vamos a ir viendo sobre la marcha. Para una explicacion completa está [esta libreta](http://nbviewer.ipython.org/github/ipython/ipython/blob/1.x/examples/notebooks/Cell%20Magics.ipynb).


En Jupyter existen varias funciones que se llaman *mágicas* las cuales empiezan siempre con %. La más común es `%matplotlib inline` para realizar gráficas dentro de la libreta y no que las genere en forma independiente. Otras muy usadas son %time Para calcular el tiempo que tarda en ejecitarse una celda, y %prun para hacer profile de la celda.

Por ejemplo

In [4]:
%time sum([x for x in range(100000)])

CPU times: user 6.31 ms, sys: 2.97 ms, total: 9.28 ms
Wall time: 9.16 ms


4999950000

In [1]:
%prun sum([x for x in range(100000)])

En general los comandos mágicos se pueden consultar con otro comando mágico

In [16]:
%quickref

## Inicializando variables en Numpy

Numpy agrega a python básicamente dos nuevos tipos o clases, de los cuales solo nos vamos a interesar por los arreglos multidimensionales o `ndarray`. La manera más sencilla de crear un array (vector o matriz) es utilizando `array` como:

In [5]:
# Crea un objeto vector
vector_a = np.array([1, 3.1416, 40, 0, 2, 5])
print(f"vector a = {vector_a}")

# Crea una matriz
matriz_A = np.array([[1, 2], [3, 4], [5, 6]])
print(f"matriz A = {matriz_A}")

vector a = [ 1.      3.1416 40.      0.      2.      5.    ]
matriz A = [[1 2]
 [3 4]
 [5 6]]


Esta es la manera más directa pero no la única (y en muchos casos la mas usada) para crear nuevos vectores multidimensionales. Existen otras maneras de generar arreglos como son las funciones:

* `arange(ini=0, fin, inc=1)`: Devuelve un ndarray iniciando en `ini` y terminando en `fin`, con incrementos de inc

* `zeros(dim)`: Devuelve un ndarray de dimensión `dim` (si es un escalar se considera un vector, si es una tupla de números entonces son las dimensiones del ndarray), con todas sus entradas en cero.
      
* `ones(dim)`: Similar a `zeros()` pero con unos.
    
* `eye(x, y=none)`: si solo se tiene el argumento `x` devuelve una matriz identidad de $x \times x$. Si se encuentra `y`, entonces una matriz diagonal rectangular de dimensión x por y.
      
* `zeros_like( x )`: Un ndarray de ceros de la misma dimensión que `x` (igual existe `ones_like`).
    
* `linspace(inicial, final, elementos)`: Devuelve un ndarray de una dimensión iniciando en inicial, hasta final de
manera que existan elementos numeros igualmente espaciados. Muy útil para graficación principalmente.
      
* `random.rand(dim1, dim2, ...)`: Devuelve un ndarray de dimensiones `dim1` por `dim2` por ... con números aleatorios
generados por una distribución uniforme entre 0 y 1.
      
Veamos unos cuantos ejemplos:

In [11]:
vZ = np.zeros((5, 2))
print(f"Un vector de ceros con 5 valores \n {vZ}")

Un vector de ceros con 5 valores 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
mO = np.ones((3, 10))
print(f"Una matriz de 3 x 10 de puros unos, \n {mO}")

Una matriz de 3 x 10 de puros unos, 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
va = np.arange(10)
print(f"va = \n {va}")

va = 
 [0 1 2 3 4 5 6 7 8 9]


In [14]:
vb = np.arange(20, -10, -5)
print(f"vb = \n {vb}")

vb = 
 [20 15 10  5  0 -5]


In [15]:
print("Y una matriz de ceros de las dimensiones de mO:")
print(np.zeros_like(mO))

Y una matriz de ceros de las dimensiones de mO:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
mA = np.random.rand(5, 12)
print("Y una matriz con números aleatorios bajo una distribución uniforme entre 0 y 1")
print(mA)

Y una matriz con números aleatorios bajo una distribución uniforme entre 0 y 1
[[0.41756815 0.23719069 0.45011275 0.00878934 0.56867781 0.47917717
  0.49926067 0.37784041 0.85939914 0.98730587 0.22341883 0.06572334]
 [0.02376598 0.47718401 0.53851203 0.85812312 0.32381489 0.37350796
  0.8350085  0.89161938 0.18378383 0.31100887 0.28370882 0.15775933]
 [0.37775829 0.72964121 0.77709929 0.64629001 0.13441796 0.35841401
  0.27429887 0.59497623 0.64214691 0.26303766 0.8469136  0.53032682]
 [0.30429183 0.55595757 0.01582923 0.02277989 0.49499906 0.28796407
  0.06948879 0.44011881 0.78908148 0.73712269 0.60230315 0.49226128]
 [0.83280511 0.51275204 0.5840413  0.47568246 0.22624613 0.57274143
  0.9009064  0.91760935 0.83625625 0.63382784 0.83256588 0.74577804]]


### Primer problema a resolver :

En la siguiente celda (o puedes crear las que consideres convenientes) crea las siguientes matrices:

* Una matriz de 4 por 6 con valores aleatorios de acuerdo a una distribución normal con media cero y varianza unitaria.
    
* Un vector de 10 elementos con valores aleatorios de números enteros entre 4 y 100
    
* Una matriz diagonal de 5 por 5 cuyos elementos de la diagonal sean (1, 2, 3, 4, 5)

In [43]:
# Introduce aqui tus respuestas

#Recuerda probar con el autocompletado de las celdas, así como la documentación en linea

matrizRand = np.random.rand(4,6);
print(matrizRand);

vector1 = np.random.randint(4,100,10);
print("\n",vector1);

matrizDiag = np.eye(5,5)*np.arange(1,6,1);
print("\n", matrizDiag);

[[8.28749762e-01 5.21123318e-01 6.28228234e-01 4.31556415e-01
  2.82669787e-06 7.45681450e-01]
 [6.46104654e-01 2.46866680e-01 9.52632396e-01 2.51714175e-01
  7.61938822e-01 7.91138539e-01]
 [6.75545114e-01 7.81641484e-01 3.46032720e-01 7.48395616e-01
  9.21275825e-01 5.44519356e-01]
 [3.53299557e-01 6.50184888e-01 7.99880655e-01 8.35295143e-01
  1.60125231e-03 6.32251118e-01]]

 [28 72 20 59 68 54 32 72 55 45]

 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


## Operaciones básicas de los ndarray

La mayoría de las operaciones que se pueden aplicar en los ndarray se encuenran en el espacio de nombres de np, y las cuales son bastante directas tal como:

    b = np.sin(a)

la cual devuelve en b un ndarray de las mismas dimensiones que a, cuyas entradas son el seno de las entradas de a (en radianes).
Así, parece inecesario explicar las funciones cos, tan, tanh, acos, asin, etc..

Otras funciones muy útiles no son tan directas. Veamos algunas:

    c = a + b

es la suma de dos ndarray, bastante obvio, lo que no lo es tanto es:

    c = a * b

la cual es un ndarray resultante de la *multiplicación punto a punto* de los elementos de a y b, asumiendo que ambos tienen
las mismas diensiones. ¿Y para aplicar un producto matricial? Pues se utiliza el comando dot (o producto punto) el cual puede ser
expresado de tres formas:

    c = np.dot(a, b)
    c = a.dot(b)
    c = a @ b

La suma de los elementos de un ndarray tambien es un método del objeto (como min, max, argmin, argmax, etc...) que tambien se pueden llamar de dos maneras diferentes (al menos):

    b = a.sum()
    b = np.sum(a)

es la suma de *todos los elementos del array* mientras que

    b = a.sum(axis=0)
    b = np.sum(a, axis=0)

es un ndarray con una dimensión menos que a, con la suma de las columnas. Veamos unos ejemplos:

In [49]:
# Vamos a generar varios ndarrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.random.rand(2, 3)

print(f"a = {a}")
print(f"b = {b}")
print(f"Suma de todos los números de b = {b.sum()}")
print(f"Media de cada columna de a = {a.mean(axis=0)} \n")
print(f"Transpuesta de a, forma larga \n {a.transpose()}")
print(f"Transpuesta de a, forma preferida \n {a.T} \n")

print(f"10 * b = {10 * b}")
print(f"a * b = {a * b} \n")

print(f"2 elevado a la matriz a = {np.power(2, a)}")
print(f"a elevada al cuadrado (elemento a elemento)")
print(np.power(a, 2))

print(f"a.dot(b.T) = {a.dot(b.T)}")
print(f"a.dot(b) debería dar error {a.dot(b)}")

a = [[1 2 3]
 [4 5 6]]
b = [[0.02883393 0.07769684 0.40686866]
 [0.57055936 0.49142395 0.83718582]]
Suma de todos los números de b = 2.4125685616542043
Media de cada columna de a = [2.5 3.5 4.5] 

Transpuesta de a, forma larga 
 [[1 4]
 [2 5]
 [3 6]]
Transpuesta de a, forma preferida 
 [[1 4]
 [2 5]
 [3 6]] 

10 * b = [[0.2883393  0.77696838 4.06868658]
 [5.70559361 4.9142395  8.37185824]]
a * b = [[0.02883393 0.15539368 1.22060597]
 [2.28223745 2.45711975 5.02311495]] 

2 elevado a la matriz a = [[ 2  4  8]
 [16 32 64]]
a elevada al cuadrado (elemento a elemento)
[[ 1  4  9]
 [16 25 36]]
a.dot(b.T) = [[1.40483358 4.06496473]
 [2.94503186 9.76247214]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Como vemos tenemos aqui una bateria completa de funciones, las cuales se aplican en un ndarray. ¿Pero que información tengo de un ndarray? ¿Como puedo componer un ndarray a partir de otros?  Asumamos por ejemplo un ndarray de una dimensión:

In [2]:
#Generamos el ndarray
a = np.arange(100)

# Checamos algunas propiedades
print(f"El número de dimensiones de a es: {a.ndim}")
print(f"Y su forma es {a.shape}")
print(f"Y tiene {a.size} elementos")

#Generamos algunos ndarrays a partir de a
b, c = a[:20], a[20:]
d, e = a[-1:-10:-1], a[10:11]
f = a[::-1]
g = a[a % 5 == 0]
h = f[[1, 15, 60]]

# Ahora trata de inferir que es lo que debe contener cada array b, c, d, e, f, g, h sin hacer ninguna prueba.

# b: sera el arreglo a pero solamente del primer elemento hasta el 19
# c: sera el arreglo a pero desde el 20 hasta el 99
# d: el arreglo a, empezando desde el último elemento, llegando hasta el elemento 10 antes del ultimo, y de ahi volviendo al último elemento (me quivoque)
# e: el arreglo incluira unicamente el elemento 10 de a, ya que el 11, en este caso, determina en donde se detiene.
# f: será el arreglo a pero al revés, empezando por el último y terminando en el primero
# g: un arreglo binario que indica en que posición hay múltiplos de 5 (casi)
# h: solo los elementos 1, 15 y 60 de el arreglo f

# Agrega ahora los print que consideres necesarios para verificar que valores tiene b, c, d, e, f, g, h
print(h)

El número de dimensiones de a es: 1
Y su forma es (100,)
Y tiene 100 elementos
[98 84 39]


A partir de una matriz (un ndarray de dos dimensiones) se pueden ejemplificar otras cosas, por ejemplo:

In [29]:
#Generamos un arreglo con 100 valores equiespaciados del seno desde 0 a 2$\pi$
a = np.sin(np.linspace(0, 2 * np.pi, 100))

#Lo convertimos en una matriz de 10 por *lo que sea*, donde *lo que sea* es 10 en este caso,
b = a.reshape((10, -1))
print("b queda como: ",b)
print(f"donde b tiene {b.ndim} dimensiones, con una forma {b.shape} y con {b.size} elementos.")

b queda como:  [[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
   2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
   4.86196736e-01  5.40640817e-01]
 [ 5.92907929e-01  6.42787610e-01  6.90079011e-01  7.34591709e-01
   7.76146464e-01  8.14575952e-01  8.49725430e-01  8.81453363e-01
   9.09631995e-01  9.34147860e-01]
 [ 9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
   9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
   9.78802446e-01  9.63842159e-01]
 [ 9.45000819e-01  9.22354294e-01  8.95993774e-01  8.66025404e-01
   8.32569855e-01  7.95761841e-01  7.55749574e-01  7.12694171e-01
   6.66769001e-01  6.18158986e-01]
 [ 5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
   3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
   9.50560433e-02  3.17279335e-02]
 [-3.17279335e-02 -9.50560433e-02 -1.58001396e-01 -2.20310533e-01
  -2.81732557e-01 -3.42020143e-01 -4.00930535e-01 -4.58226522e-01
  -5.13677392e-01 

In [31]:
#Si queremos convertir un ndarray a un array de una sola dimension (desenrrollar la matriz podría ser el término)
c = b.ravel()

print("La diferencia de a y c sería")
print((a - c).sum())

La diferencia de a y c sería
0.0


In [3]:
# Si queremos hacer que un vector se comporte como un vector renglon
a = np.arange(30).reshape(1,-1)
print(f"a es de forma {a.shape}")

# Y si queremos que sea un vector columna hacemos esto
b = np.linspace(30, 35, 30).reshape(-1,1)
print(f"b es de forma {b.shape}")

# Y para hacer una concatenacion de columnas entonces utilizamps la forma especial np.c_[]
c = np.c_[a.T, b]
print(f"c es de forma {c.shape}")

#Y una concatenación de renglones es por lo tanto
d = np.r_[a, b.T]
print(f"d es de forma {d.shape}")

a es de forma (1, 30)
b es de forma (30, 1)
c es de forma (30, 2)
d es de forma (2, 30)


### Segundo problema a resolver

Realiza lo siguiente:

* Genera una matriz de 100 por 5 de forma que en cada columna tengamos lo siguiente:
    
    - En la primer columna los valores entre -1 y 1, equiespaciados
    - En la segunda columna el valor de seno para los valores de la primer columna
    - En la tercer columna el valor de la función logística de los valores de la primer columna, la cual es $g(x) = \frac{1}{1 + \exp(-x)}$
    - En la cuarta columna 1 si el valor de la segunda columna es mayor que cero y -1 en otro caso (revisa la función np.where)
    - En la quinta columna valores aleatorios de acuerdo a una distribución gaussiana con media 1 y varianza 0.5
        
* Encuentra un arreglo con todos los valores de la función logística, cuando el valor absoluto del seno de x es menor a 0.5
    
* Convierte este arraglo en una matriz con 5 columnas y los renglones que sean necesarios.
        

In [44]:
# Escribe aqui tu código
a = np.linspace(-1,1,100).reshape(100,1)
b = np.sin(a)
c = (1/(1+np.exp(-a)))
d = np.where(b>1,1,0)
e = np.random.normal(1, np.sqrt(0.5),100).reshape(100,1)

matriz = np.c_[a,b,c,d,e]
print(matriz)

[[-1.00000000e+00 -8.41470985e-01  2.68941421e-01  0.00000000e+00
   1.76822511e+00]
 [-9.79797980e-01 -8.30384824e-01  2.72931871e-01  0.00000000e+00
   6.76998212e-01]
 [-9.59595960e-01 -8.18959776e-01  2.76959098e-01  0.00000000e+00
   1.42504394e+00]
 [-9.39393939e-01 -8.07200505e-01  2.81022780e-01  0.00000000e+00
   6.24790775e-01]
 [-9.19191919e-01 -7.95111809e-01  2.85122575e-01  0.00000000e+00
  -4.47023219e-01]
 [-8.98989899e-01 -7.82698621e-01  2.89258118e-01  0.00000000e+00
  -7.63129767e-02]
 [-8.78787879e-01 -7.69966008e-01  2.93429023e-01  0.00000000e+00
   1.47597066e+00]
 [-8.58585859e-01 -7.56919167e-01  2.97634885e-01  0.00000000e+00
   1.99946344e+00]
 [-8.38383838e-01 -7.43563420e-01  3.01875275e-01  0.00000000e+00
  -1.62427470e-03]
 [-8.18181818e-01 -7.29904220e-01  3.06149746e-01  0.00000000e+00
   1.99358898e+00]
 [-7.97979798e-01 -7.15947140e-01  3.10457825e-01  0.00000000e+00
   1.93063704e+00]
 [-7.77777778e-01 -7.01697876e-01  3.14799023e-01  0.00000000e+00

Además de estas funciones, numpy cuenta con funciones del algebra lineal altamente optimizadas (aunque no paralelizadas), las cuales son (entre otras):

* `np.linalg.inv(a)`: Inversa de a
* `np.linalg.pinv(a)`: Pseudoinversa de Ross-Penrose de a (muy útil para nosotros)
* `np.linalg.det(a)`: determinante de a
* `np.linalg.eig(a)`: eigenvalores y eigenvectores de a
* `np.linalg.svd(a)`: Valores singulares de a

## Haciendo gráficas sencillas con Matplotlib

La mejor manera de mostrar como funcionan las facilidades que ofrece matplotlib, es mostrando directamente su uso más sencillo,
así que veamos un ejemplo muy simple. Es importante recordar que en la primer celda de esta libreta se definió la manera de realizar las gráficas (dentro del documento y no como figuras aparte), así como se cargo matplotlib en el espacio de nombres plt.

In [ ]:
# Vamos a hacerlo pasito a pasito

# Primero obtenemos un vector x
x = np.linspace(-np.pi, np.pi, 1000)

# Luego obtenemos un vector y bastante trivial
y = np.sin(x)

# Y ahora hacemos una gráfica bastante básica de x y y
plt.plot(x, y)
plt.xlabel("el eje de las x's")
plt.ylabel("el eje de las y's")
plt.title("Este es un plot bastante trivial y sin mucho chiste")

# Bueno como la gráfica no esta muy bien a lo mejor se ve mejor si modificamos los limites de los ejes
plt.axis([-3.1416, 3.1416, -1.1, 1.1])

Aunque a veces queremos hacer unas gráficas más bien indicativas por lo que un estilo más informal podría ser útil:


In [ ]:
with plt.xkcd():
    plt.plot(x, y)
    plt.xlabel("el eje de las x's")
    plt.ylabel("el eje de las y's")
    plt.title("Este es un plot bastante trivial y sin mucho chiste")
    plt.axis([-3.1416, 3.1416, -1.1, 1.1])

Hay que tener mucho cuidado, ya que si no se utiliza plt.xkcd() dentro de un with, entonces va a modificar todas las graficas que se realicen en la libreta (a veces es deseable, pero es una mejor práctica de programación hacerlo así).

In [ ]:
with plt.style.context(('ggplot')):
    plt.plot(x, y)
    plt.xlabel("el eje de las x's")
    plt.ylabel("el eje de las y's")
    plt.title("Este es un plot bastante trivial y sin mucho chiste")
    plt.axis([-3.1416, 3.1416, -1.1, 1.1])

Ahora hagamos una gráfica con varios valores diferentes

In [ ]:
plt.plot(x, np.sin(x), label='seno')

plt.plot(x, 1/(1 + np.exp(-x)), label=u"logística")

plt.plot(x, (0.2 * x * x) - 0.5, label=r'$0.2 x^2 - 0.5$')

plt.axis([-3.1416, 3.1416, -1.1, 1.4])

plt.title("Tres funciones piteras juntas")
plt.xlabel(r"$\theta$ (rad)")
plt.ylabel("magnitud")

plt.legend(loc=0)

Hay muchos tipos de funciones, lo mejor para saber como ustilizar matplotlib es ver la galeria de ejemplo que se encuentran en la ayuda,
y pueden consultarse en http://matplotlib.org/gallery.html (al darle click a una imagen se puede ver el código que la genera).

Por ejemplo si queremos una gráfica tipo pay:

In [ ]:
labels = 'Tortas', 'Taquitos', 'Burros', 'Ensaladas'
porcentajes = [15, 30, 45, 10]
colores = ['yellowgreen', 'gold', 'lightskyblue', 'lightcoral']
separa = (0, 0.1, 0, 0) # solo separa la segunda rebanada (i.e. 'Taquitos')

plt.pie(
    porcentajes, explode=separa, labels=labels, colors=colores,
    autopct='%1.1f%%', shadow=True, startangle=90
)
plt.axis('equal') #Para que el pay se vea como un círculo
plt.xlabel(u'Lo que como cuando me quedo en la UNISON a mediodía')


O si queremos una gráfica tipo contorno con todo y datos

In [ ]:
import matplotlib.cm as cm

delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = (Z1 - Z2) * 2

CS = plt.contour(X, Y, Z)
plt.clabel(CS, fontsize=10)
plt.title('Grafica simple de contorno')
plt.show()

Por último, un detalle muy importante y que puede ser de mucha utilidad: La generación de subplots. Una figura puede contener varias subgraficas, para esto hay que especificar en cuantas gráficas vamos a dividir la figura en forma de renglones y columnas, y luego seleccionar la subgráfica en la que vamos a graficar. Por ejemplo

    plt.subplot(2,2,1)
    
significa que la figura la vamos a dividir en 2 renglones y dos columnas (cuatro subgráficas) y vamos a escribir sobre la subgráfica 1. Lo mejor es ilustrarlo con un ejemplo muy simple.

In [ ]:
x = np.linspace(0, 5, 1000)
y1 = np.exp(-0.2 * x) * np.cos(2 * np.pi * x)
y2 = np.cos(2 * np.pi * x)
y3 = np.exp(0.2 * x) * np.cos(2 * np.pi * x)
y4 = np.exp(-0.1 * x)

plt.subplot(2, 2, 1)
plt.plot(x, y1)
plt.title('Estable subamortiguado')

plt.subplot(2, 2, 2)
plt.plot(x, y2)
plt.title('Criticamente estable')

plt.subplot(2, 2, 3)
plt.plot(x, y3)
plt.title('inestable')

plt.subplot(2, 2, 4)
plt.plot(x, y4)
plt.title('Estable sobreamortiguado')



### Ultimo trabajo

Realiza lo siguiente en varias celdas abajo de esta:

* Genera un vector de 1000 datos aleatorios distribuidos de acuerdo a una gaussiana con media 3 y varianza .5, y otro vector con 1000 datos aleatorios distribuidos con una media 0 y una varianza unitaria. Al concatenar los dos vectores, estás generando una serie de datos proveniente de una distribución conocida como suma de gaussianas. Para ver como es esta distribución de datos, grafíca un histograma (con un número suficiente de bins).

* Genera un vector de datos de entrada `x = np.linspace(0, 1, 1000)` y grafica $\sin(2\pi x)$, $\sin(4\pi x)$, $\sin(8\pi x)$. ¿Que conlusión puedes sacar al respecto? Realiza la gráfica con titulo, ejes, etiquetas y todo lo necesario para que sea publicable.

* Grafíca la función $e^{-t}\cos(2\pi t)$ para $t \in [0, 5]$. Asegurate que la gráfica sea una linea punteada de color rojo, que la gráfica tenga título, etiqueta en el eje de $t$ (tiempo), etiqueta en el eje de $y$ (voltaje en $\mu$V), y una nota donde se escriba la ecuación simulada.

* Copia el ejemplo de la galería de matplotlib http://matplotlib.org/examples/pylab_examples/shading_example.html y modificalo para que se grafique dentro de la libreta. Una vez funcionando, comenta *cada linea de código* dejando bien claro **en español y con tus palabras** que es lo que hace cada una de las lineas.

In [ ]:
#Agrega aqui el primer problema y resualve cada problema en una celda independiente.